[workspace]
resolver = "2"
members = [
	"crates/shroom-net",
	"crates/shroom-pkt",
	"crates/shroom-pkt-derive",
	"crates/shroom-crypto",
	"crates/shroom-wz",
	"crates/shroom-img",
	"crates/img-extractor",
]
