[package]
name = "shroom-wz"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
binrw = "0.13"
bytemuck = "1.16.0"
image = "0.25.2"
shroom-crypto = { version = "0.1.0", path = "../shroom-crypto" }
shroom-img = { version = "0.1.0", path = "../shroom-img" }
